---
title: "mid-term multivariate analysis"
author: "muqiitsaputra"
date: "3/17/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
1) Syntax soal nomor 1
```{r}
# Input data
evalues <- matrix(c(5.100851, 0, 0, 1.406176), nrow = 2)
evectors <- matrix(c(-0.6314539, -0.7754134, 0.7754134, -0.6314539), ncol = 2)
mu0 <- c(4, 10)
xbr <- c(4.64, 9.965)
S1 <- evectors %*% evalues %*% solve(evectors) # S1 maksudnya matriks Sigma utk No. 1

# Hotelling's T2 Mean Vector
n <- 20
T2 <- n * t(xbr - mu0) %*% solve(S1) %*% (xbr - mu0)
p <- 2
a <- .10
T2tab = p*(n - 1) / (n - p - 1) * qf(1 - a, p, n - p - 1)

if(T2 > T2tab){
  cat(T2, ">", T2tab, "\nTolak H0")
}else{
  cat(T2, "<", T2tab,"\nGagal tolak H0")
}

cat("\n---------------------------------------------------------\n")
# Selang kepercayaan 90%
ci1 <- xbr[1] + c(c(-1,1) * (T2tab * S1[1,1] / (1/n))^0.5)
ci2 <- xbr[2] + c(c(-1,1) * (T2tab * S1[2,2] / (1/n))^0.5)
cat("xbar1 \n", xbr[1], "\nxbar2\n", xbr[2])
cat("\n\nSelang xbar1 (90%) \n", ci1[1], ci1[2], "\n\nSelang xbar2 (90%)\n", ci2[1], ci2[2])
```

2) Syntax soal nomor 2
```{r}
# Input data
n <- 100
xbar <- c(3.23, 3.22, 3.13, 3.11)
C <- matrix(c(-1,-1,1,1,1,-1,1,-1,1,-1,-1,1), ncol = 4, byrow = TRUE) #contrast matrix, sesuaikan dengan soal
R <- matrix(c(1, 0.75, 0.727, 0.588, 0.75, 1, 0.629, 0.095, 0.727, 0.629, 1, 0.684, 0.588, 0.095, 0.684, 1), ncol = 4) # matrix correlation
sd <- c(0.251, 0.149, 0.254, 0.141) # standar deviasi
S <- cor2cov(R, sd) # matrix variance-covariance

cat("Matriks xbar\n\n")
xbar

cat("Matriks C\n\n")
C

cat("Matriks S\n\n")
S

cat("---------------------------------------------------------\n")
cat("T2 Hotelling's \n")
# Uji Beda Rata-rata pada Repeated Measure (Statistic Uji T2 Hotelling's)
p <- 4 - 1
a <- .05
T2 = n * t(C %*% xbar) %*% solve(C %*% S %*% t(C)) %*% (C %*% xbar)
T2tab = p*(n-1) / (n-p) * qf(1 - a, p, n - p)

if(T2 > T2tab){
  cat(T2, ">", T2tab, "\nTolak H0")
}else{
  cat(T2, "<", T2tab,"\nGagal tolak H0")
}
cat("\n---------------------------------------------------------\n")

# Menghitung Selang Kepercayaan
cat("Menghitung Selang Kepercayaan \n")
# C1 =  (miu3 + miu 4) - (miu1 + miu2) #
b = 1 #baris pada matrix C
C1 <- (C[1,1:4] %*% xbar) + c(-1,1) * (T2tab * (C[1,1:4]%*%S%*%C[1,1:4]) / n)^0.5
cat("(miu3 + miu 4) - (miu1 + miu2)\n")
cat("Selang (95%) \n", C1[1], C1[2])

# C2 =  (miu1 + miu 3) - (miu2 + miu4) #
b = 2 #baris pada matrix C
C2 <- (C[2,1:4] %*% xbar) + c(-1,1) * (T2tab * (C[2,1:4]%*%S%*%C[2,1:4]) / n)^0.5
cat("(miu1 + miu 3) - (miu2 + miu4)\n")
cat("Selang (95%) \n", C2[1], C2[2])

# C3 =  (miu1 + miu 4) - (miu2 + miu3) #
b = 3 #baris pada matrix C, menunjukkan interaksi
C3 <- (C[3,1:4] %*% xbar) + c(-1,1) * (T2tab * (C[3,1:4]%*%S%*%C[3,1:4]) / n)^0.5
cat("(miu1 + miu 4) - (miu2 + miu3)\n")
cat("Selang (95%) \n", C3[1], C3[2])

cat("\n---------------------------------------------------------")
```

3) Syntax soal nomor 3
refers to: http://www.sthda.com/english/wiki/manova-test-in-r-multivariate-analysis-of-variance
```{r}
# Input data
kode_kabkot <- c(rep(71, times = 16), rep(72, times = 8), rep(73, times = 12), rep(74, times = 10), rep(75, times = 13))
x1 <- c(0.17, 0.49, 0.25, 0.05, 0.04, 0.06, 0.17, 0.12, 0.11, 0.1, 0.13, 0.38, 0.24, 0.23, 0.29, 0.1, 0.6, 0.15, 0.47, 0.55, 0.27, 0.18, 0.04, 0.05, 0.13, 0.88, 0.16, 0.11, 0.79, 0.43, 0.14, 0.09, 0.27, 0.69, 0.07, 0.2, 0.35, 0.49, 0.71, 1.03, 0.06, 0.74,1.67, 0.56, 0.13, 0.4, 0.08, 3.89, 0.31, 0.61, 0.41, 0.18, 0.09, 0.38, 0.55, 0.47, 1.42, 0.37, 0.44)
x2 <- c(0, 0.02, 0.01, 0.01, 0, 0.01, 0.01, 0, 0.03, 0.01, 0.01, 0.02, 0.01, 0, 0.01, 0.01, 0.24, 0.08, 0.06, 0.18, 0.07, 0.11, 0.08, 0.24, 0.03, 0.02, 0.05, 0.02, 0.08, 0.03, 0.06, 0.02, 0.04, 0.02, 0.02, 0.01, 0.06, 0.07, 0.08, 0.27, 0.02, 0, 0.02, 0.01, 0.01, 0, 0.01, 0.07, 0.05, 0.04, 0.03, 0.09, 0.05, 0.02, 0.02, 0.04, 0.01, 0, 0)
x3 <- c(0.45, 1.25, 0.5, 0, 0, 0.09, 0.4, 0.17, 0.14, 0.14, 0.17, 0.64, 0.5, 0.5, 0.5, 0.14, 1.57, 0.33, 1, 1.44, 0.5, 0.5, 0, 0, 0.17, 2.75, 0.39, 0.17, 2.45, 1, 0.2, 0.13, 0.5, 2, 0.1, 0.5, 0.56, 1.25, 2, 3.5, 0.04, 2.13, 6, 1.5, 0.2, 0.75, 0.01, 6, 0.56, 2, 0.75, 0.5, 0.14, 0.67, 1.33, 1, 4.33, 0.57, 1)
kode_kabkot <- as.factor(kode_kabkot)

# Manova test
mod <- manova(cbind(x1, x2, x3) ~ kode_kabkot)
summary(mod)
cat("--------------------------------------------------------------------\n\n")
summary.aov(mod)
```