---
title: "repeated measure"
author: "muqiitsaputra"
date: "2/21/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
######## Richard Johnson Ed. 5 p. 281 ########
x1 <- c(426,253,359,432,405,324,310,326,375,286,349,429,348,412,347,434,364,420,397)
x2 <- c(609,236,433,431,426,438,312,326,447,286,382,410,377,473,326,458,367,395,556)
x3 <- c(556,392,349,522,513,507,410,350,547,403,473,488,447,472,455,637,432,508,645)
x4 <- c(600,395,357,600,513,539,456,504,548,422,497,547,514,446,468,524,469,531,625)
x <- cbind(x1, x2, x3, x4)
n <- nrow(x)
j <- matrix(1, n, n)
C <- matrix(c(-1,-1,1,1,1,-1,1,-1,1,-1,-1,1), ncol = 4, byrow = TRUE) #contrast matrix, sesuaikan dengan soal
S <- 1/(n-1) * t(x) %*% (diag(n) - j/n) %*% x
cat("Matriks x\n\n")
x

cat("Matriks C\n\n")
C

cat("Matriks S\n\n")
S

# Uji Beda Rata-rata pada Repeated Measure (Statistic Uji T2 Hotelling's)
xbar <- matrix(c(mean(x1), mean(x2), mean(x3), mean(x4)), 4)
p <- ncol(x) - 1
a <- .05
T2 = n * t(C %*% xbar) %*% solve(C %*% S %*% t(C)) %*% (C %*% xbar)
T2tab = p*(n-1) / (n-p) * qf(1 - a, p, n - p)

if(T2 > T2tab){
  cat(T2, ">", T2tab, "\nTolak H0")
}else{
  cat(T2, "<", T2tab,"\nGagal tolak H0")
}

# Menghitung Selang Kepercayaan
# C1 =  (miu3 + miu 4) - (miu1 + miu2) #
b = 1 #baris pada matrix C
C1 <- (C[b,1:4] %*% xbar) + c(-1,1) * (T2tab * (C[b,1:4]%*%S%*%C[b,1:4]) / n)^0.5
cat("(miu3 + miu 4) - (miu1 + miu2)\n")
cat("Selang (95%) \n", C1[1], C1[2])

# C2 =  (miu1 + miu 3) - (miu2 + miu4) #
b = 2 #baris pada matrix C
C2 <- (C[b,1:4] %*% xbar) + c(-1,1) * (T2tab * (C[b,1:4]%*%S%*%C[b,1:4]) / n)^0.5
cat("(miu1 + miu 3) - (miu2 + miu4)\n")
cat("Selang (95%) \n", C2[1], C2[2])

# C3 =  (miu1 + miu 4) - (miu2 + miu3) #
b = 3 #baris pada matrix C, menunjukkan interaksi
C3 <- (C[b,1:4] %*% xbar) + c(-1,1) * (T2tab * (C[b,1:4]%*%S%*%C[b,1:4]) / n)^0.5
cat("(miu1 + miu 4) - (miu2 + miu3)\n")
cat("Selang (95%) \n", C3[1], C3[2])
```

